/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -C --input cmdline.ggo --output-dir ../src --unamed-opts=SCRIPTS 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "Distributed execution of commands.";

const char *gengetopt_args_info_usage = "Usage: distexec [OPTIONS]... -- command";

const char *gengetopt_args_info_versiontext = "This software is supplied WITHOUT ANY WARRANTY; without even the implied\nwarranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. This is\nfree software, and you are welcome to redistribute it under certain\nconditions; see the file COPYING for details.";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_detailed_help[] = {
  "  -h, --help                    Print help and exit",
  "      --detailed-help           Print help, including all details and hidden\n                                  options, and exit",
  "      --full-help               Print help, including hidden options, and exit",
  "  -V, --version                 Print version and exit",
  "\nGeneral:",
  "  -C, --config=FILE             Configuration file",
  "  -O, --output                  Use --stdout and --stdin combined",
  "      --stdout                  Print remote stdout",
  "      --stderr                  Print remote stderr",
  "  -P, --progress                Print progressbar",
  "  -l, --list                    Print hosts",
  "\nPlugins:",
  "      --plugin-path=PATH        Path to plugins\n                                  (default=`/usr/local/share/distexec/plugins')",
  "  -p, --plugin=NAME             Plugin to load",
  "\nFiltering:",
  "  -F, --filter=FILTER           Filter query",
  "  The filter query is passed to each collector.\n  Each collector might use other query syntax.\n\n  This just sucks.",
  "  -g, --grep=REGEX              Filter output ",
  "\nExecution:",
  "  -E, --env=KEY=VAL             Environment variable",
  "\nConcurrency:",
  "  -c, --concurrent=INT          Number of concurrent connection threads\n                                  (default=`1')",
  "\nLogging:",
  "  -S, --log-split               Split logfile per host (needs --log-file)",
  "  -L, --log-file=FILE           Log to file instead of stdout",
  "      --log-format-date=STRFTIME\n                                Date format  (default=`%Y-%m-%d')",
  "      --log-format-time=STRFTIME\n                                Time format  (default=`%H:%M:%S')",
  "      --log-format=FORMAT       Log format",
  "   Format variables:\n  	%D  - Date (See --log-format-date)\n  	%T  - Time (See --log-format-time)\n  	%X  - Microseconds part of current second\n  	%N  - Logger Name\n  	%L  - Log Level\n  	%M  - Log Message\n  	%f  - File\n  	%m  - Function/Method\n  	%l  - Line Number\n\n  Default format: %D %T.%X [%N] %L %f:%m:%l: %M\n",
  "\nOther:",
  "      --debug                   Enable debug messages  (default=on)",
  "\nSee the distexec man page for examples.",
    0
};
static void
init_full_help_array(void)
{
  gengetopt_args_info_full_help[0] = gengetopt_args_info_detailed_help[0];
  gengetopt_args_info_full_help[1] = gengetopt_args_info_detailed_help[1];
  gengetopt_args_info_full_help[2] = gengetopt_args_info_detailed_help[2];
  gengetopt_args_info_full_help[3] = gengetopt_args_info_detailed_help[3];
  gengetopt_args_info_full_help[4] = gengetopt_args_info_detailed_help[4];
  gengetopt_args_info_full_help[5] = gengetopt_args_info_detailed_help[5];
  gengetopt_args_info_full_help[6] = gengetopt_args_info_detailed_help[6];
  gengetopt_args_info_full_help[7] = gengetopt_args_info_detailed_help[7];
  gengetopt_args_info_full_help[8] = gengetopt_args_info_detailed_help[8];
  gengetopt_args_info_full_help[9] = gengetopt_args_info_detailed_help[9];
  gengetopt_args_info_full_help[10] = gengetopt_args_info_detailed_help[10];
  gengetopt_args_info_full_help[11] = gengetopt_args_info_detailed_help[11];
  gengetopt_args_info_full_help[12] = gengetopt_args_info_detailed_help[12];
  gengetopt_args_info_full_help[13] = gengetopt_args_info_detailed_help[13];
  gengetopt_args_info_full_help[14] = gengetopt_args_info_detailed_help[14];
  gengetopt_args_info_full_help[15] = gengetopt_args_info_detailed_help[15];
  gengetopt_args_info_full_help[16] = gengetopt_args_info_detailed_help[17];
  gengetopt_args_info_full_help[17] = gengetopt_args_info_detailed_help[18];
  gengetopt_args_info_full_help[18] = gengetopt_args_info_detailed_help[19];
  gengetopt_args_info_full_help[19] = gengetopt_args_info_detailed_help[20];
  gengetopt_args_info_full_help[20] = gengetopt_args_info_detailed_help[21];
  gengetopt_args_info_full_help[21] = gengetopt_args_info_detailed_help[22];
  gengetopt_args_info_full_help[22] = gengetopt_args_info_detailed_help[23];
  gengetopt_args_info_full_help[23] = gengetopt_args_info_detailed_help[24];
  gengetopt_args_info_full_help[24] = gengetopt_args_info_detailed_help[25];
  gengetopt_args_info_full_help[25] = gengetopt_args_info_detailed_help[26];
  gengetopt_args_info_full_help[26] = gengetopt_args_info_detailed_help[27];
  gengetopt_args_info_full_help[27] = gengetopt_args_info_detailed_help[29];
  gengetopt_args_info_full_help[28] = gengetopt_args_info_detailed_help[30];
  gengetopt_args_info_full_help[29] = gengetopt_args_info_detailed_help[31];
  gengetopt_args_info_full_help[30] = 0; 
  
}

const char *gengetopt_args_info_full_help[31];

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_detailed_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_detailed_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_detailed_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_detailed_help[3];
  gengetopt_args_info_help[4] = gengetopt_args_info_detailed_help[4];
  gengetopt_args_info_help[5] = gengetopt_args_info_detailed_help[5];
  gengetopt_args_info_help[6] = gengetopt_args_info_detailed_help[6];
  gengetopt_args_info_help[7] = gengetopt_args_info_detailed_help[7];
  gengetopt_args_info_help[8] = gengetopt_args_info_detailed_help[8];
  gengetopt_args_info_help[9] = gengetopt_args_info_detailed_help[9];
  gengetopt_args_info_help[10] = gengetopt_args_info_detailed_help[10];
  gengetopt_args_info_help[11] = gengetopt_args_info_detailed_help[11];
  gengetopt_args_info_help[12] = gengetopt_args_info_detailed_help[12];
  gengetopt_args_info_help[13] = gengetopt_args_info_detailed_help[13];
  gengetopt_args_info_help[14] = gengetopt_args_info_detailed_help[14];
  gengetopt_args_info_help[15] = gengetopt_args_info_detailed_help[15];
  gengetopt_args_info_help[16] = gengetopt_args_info_detailed_help[17];
  gengetopt_args_info_help[17] = gengetopt_args_info_detailed_help[18];
  gengetopt_args_info_help[18] = gengetopt_args_info_detailed_help[19];
  gengetopt_args_info_help[19] = gengetopt_args_info_detailed_help[20];
  gengetopt_args_info_help[20] = gengetopt_args_info_detailed_help[21];
  gengetopt_args_info_help[21] = gengetopt_args_info_detailed_help[22];
  gengetopt_args_info_help[22] = gengetopt_args_info_detailed_help[23];
  gengetopt_args_info_help[23] = gengetopt_args_info_detailed_help[24];
  gengetopt_args_info_help[24] = gengetopt_args_info_detailed_help[29];
  gengetopt_args_info_help[25] = gengetopt_args_info_detailed_help[30];
  gengetopt_args_info_help[26] = gengetopt_args_info_detailed_help[31];
  gengetopt_args_info_help[27] = 0; 
  
}

const char *gengetopt_args_info_help[28];

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->detailed_help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->config_given = 0 ;
  args_info->output_given = 0 ;
  args_info->stdout_given = 0 ;
  args_info->stderr_given = 0 ;
  args_info->progress_given = 0 ;
  args_info->list_given = 0 ;
  args_info->plugin_path_given = 0 ;
  args_info->plugin_given = 0 ;
  args_info->filter_given = 0 ;
  args_info->grep_given = 0 ;
  args_info->env_given = 0 ;
  args_info->concurrent_given = 0 ;
  args_info->log_split_given = 0 ;
  args_info->log_file_given = 0 ;
  args_info->log_format_date_given = 0 ;
  args_info->log_format_time_given = 0 ;
  args_info->log_format_given = 0 ;
  args_info->debug_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->config_arg = NULL;
  args_info->config_orig = NULL;
  args_info->plugin_path_arg = NULL;
  args_info->plugin_path_orig = NULL;
  args_info->plugin_arg = NULL;
  args_info->plugin_orig = NULL;
  args_info->filter_arg = NULL;
  args_info->filter_orig = NULL;
  args_info->grep_arg = NULL;
  args_info->grep_orig = NULL;
  args_info->env_arg = NULL;
  args_info->env_orig = NULL;
  args_info->concurrent_arg = 1;
  args_info->concurrent_orig = NULL;
  args_info->log_file_arg = NULL;
  args_info->log_file_orig = NULL;
  args_info->log_format_date_arg = gengetopt_strdup ("%Y-%m-%d");
  args_info->log_format_date_orig = NULL;
  args_info->log_format_time_arg = gengetopt_strdup ("%H:%M:%S");
  args_info->log_format_time_orig = NULL;
  args_info->log_format_arg = NULL;
  args_info->log_format_orig = NULL;
  args_info->debug_flag = 1;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  init_full_help_array(); 
  init_help_array(); 
  args_info->help_help = gengetopt_args_info_detailed_help[0] ;
  args_info->detailed_help_help = gengetopt_args_info_detailed_help[1] ;
  args_info->full_help_help = gengetopt_args_info_detailed_help[2] ;
  args_info->version_help = gengetopt_args_info_detailed_help[3] ;
  args_info->config_help = gengetopt_args_info_detailed_help[5] ;
  args_info->config_min = 0;
  args_info->config_max = 0;
  args_info->output_help = gengetopt_args_info_detailed_help[6] ;
  args_info->stdout_help = gengetopt_args_info_detailed_help[7] ;
  args_info->stderr_help = gengetopt_args_info_detailed_help[8] ;
  args_info->progress_help = gengetopt_args_info_detailed_help[9] ;
  args_info->list_help = gengetopt_args_info_detailed_help[10] ;
  args_info->plugin_path_help = gengetopt_args_info_detailed_help[12] ;
  args_info->plugin_path_min = 0;
  args_info->plugin_path_max = 0;
  args_info->plugin_help = gengetopt_args_info_detailed_help[13] ;
  args_info->plugin_min = 0;
  args_info->plugin_max = 0;
  args_info->filter_help = gengetopt_args_info_detailed_help[15] ;
  args_info->grep_help = gengetopt_args_info_detailed_help[17] ;
  args_info->grep_min = 0;
  args_info->grep_max = 0;
  args_info->env_help = gengetopt_args_info_detailed_help[19] ;
  args_info->env_min = 0;
  args_info->env_max = 0;
  args_info->concurrent_help = gengetopt_args_info_detailed_help[21] ;
  args_info->log_split_help = gengetopt_args_info_detailed_help[23] ;
  args_info->log_file_help = gengetopt_args_info_detailed_help[24] ;
  args_info->log_format_date_help = gengetopt_args_info_detailed_help[25] ;
  args_info->log_format_time_help = gengetopt_args_info_detailed_help[26] ;
  args_info->log_format_help = gengetopt_args_info_detailed_help[27] ;
  args_info->debug_help = gengetopt_args_info_detailed_help[30] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
cmdline_parser_print_detailed_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_detailed_help[i])
    printf("%s\n", gengetopt_args_info_detailed_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}


static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_multiple_string_field (args_info->config_given, &(args_info->config_arg), &(args_info->config_orig));
  free_multiple_string_field (args_info->plugin_path_given, &(args_info->plugin_path_arg), &(args_info->plugin_path_orig));
  free_multiple_string_field (args_info->plugin_given, &(args_info->plugin_arg), &(args_info->plugin_orig));
  free_string_field (&(args_info->filter_arg));
  free_string_field (&(args_info->filter_orig));
  free_multiple_string_field (args_info->grep_given, &(args_info->grep_arg), &(args_info->grep_orig));
  free_multiple_string_field (args_info->env_given, &(args_info->env_arg), &(args_info->env_orig));
  free_string_field (&(args_info->concurrent_orig));
  free_string_field (&(args_info->log_file_arg));
  free_string_field (&(args_info->log_file_orig));
  free_string_field (&(args_info->log_format_date_arg));
  free_string_field (&(args_info->log_format_date_orig));
  free_string_field (&(args_info->log_format_time_arg));
  free_string_field (&(args_info->log_format_time_orig));
  free_string_field (&(args_info->log_format_arg));
  free_string_field (&(args_info->log_format_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->detailed_help_given)
    write_into_file(outfile, "detailed-help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  write_multiple_into_file(outfile, args_info->config_given, "config", args_info->config_orig, 0);
  if (args_info->output_given)
    write_into_file(outfile, "output", 0, 0 );
  if (args_info->stdout_given)
    write_into_file(outfile, "stdout", 0, 0 );
  if (args_info->stderr_given)
    write_into_file(outfile, "stderr", 0, 0 );
  if (args_info->progress_given)
    write_into_file(outfile, "progress", 0, 0 );
  if (args_info->list_given)
    write_into_file(outfile, "list", 0, 0 );
  write_multiple_into_file(outfile, args_info->plugin_path_given, "plugin-path", args_info->plugin_path_orig, 0);
  write_multiple_into_file(outfile, args_info->plugin_given, "plugin", args_info->plugin_orig, 0);
  if (args_info->filter_given)
    write_into_file(outfile, "filter", args_info->filter_orig, 0);
  write_multiple_into_file(outfile, args_info->grep_given, "grep", args_info->grep_orig, 0);
  write_multiple_into_file(outfile, args_info->env_given, "env", args_info->env_orig, 0);
  if (args_info->concurrent_given)
    write_into_file(outfile, "concurrent", args_info->concurrent_orig, 0);
  if (args_info->log_split_given)
    write_into_file(outfile, "log-split", 0, 0 );
  if (args_info->log_file_given)
    write_into_file(outfile, "log-file", args_info->log_file_orig, 0);
  if (args_info->log_format_date_given)
    write_into_file(outfile, "log-format-date", args_info->log_format_date_orig, 0);
  if (args_info->log_format_time_given)
    write_into_file(outfile, "log-format-time", args_info->log_format_time_orig, 0);
  if (args_info->log_format_given)
    write_into_file(outfile, "log-format", args_info->log_format_orig, 0);
  if (args_info->debug_given)
    write_into_file(outfile, "debug", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->config_given, args_info->config_min, args_info->config_max, "'--config' ('-C')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->plugin_path_given, args_info->plugin_path_min, args_info->plugin_path_max, "'--plugin-path'"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->plugin_given, args_info->plugin_min, args_info->plugin_max, "'--plugin' ('-p')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->grep_given, args_info->grep_min, args_info->grep_max, "'--grep' ('-g')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->env_given, args_info->env_min, args_info->env_max, "'--env' ('-E')"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  union generic_value multiple_default_value;

  struct generic_list * config_list = NULL;
  struct generic_list * plugin_path_list = NULL;
  struct generic_list * plugin_list = NULL;
  struct generic_list * grep_list = NULL;
  struct generic_list * env_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "detailed-help",	0, NULL, 0 },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "config",	1, NULL, 'C' },
        { "output",	0, NULL, 'O' },
        { "stdout",	0, NULL, 0 },
        { "stderr",	0, NULL, 0 },
        { "progress",	0, NULL, 'P' },
        { "list",	0, NULL, 'l' },
        { "plugin-path",	1, NULL, 0 },
        { "plugin",	1, NULL, 'p' },
        { "filter",	1, NULL, 'F' },
        { "grep",	1, NULL, 'g' },
        { "env",	1, NULL, 'E' },
        { "concurrent",	1, NULL, 'c' },
        { "log-split",	0, NULL, 'S' },
        { "log-file",	1, NULL, 'L' },
        { "log-format-date",	1, NULL, 0 },
        { "log-format-time",	1, NULL, 0 },
        { "log-format",	1, NULL, 0 },
        { "debug",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVC:OPlp:F:g:E:c:SL:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'C':	/* Configuration file.  */
        
          if (update_multiple_arg_temp(&config_list, 
              &(local_args_info.config_given), optarg, 0, 0, ARG_STRING,
              "config", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'O':	/* Use --stdout and --stdin combined.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->output_given),
              &(local_args_info.output_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "output", 'O',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* Print progressbar.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->progress_given),
              &(local_args_info.progress_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "progress", 'P',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Print hosts.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->list_given),
              &(local_args_info.list_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "list", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Plugin to load.  */
        
          if (update_multiple_arg_temp(&plugin_list, 
              &(local_args_info.plugin_given), optarg, 0, 0, ARG_STRING,
              "plugin", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'F':	/* Filter query.  */
        
        
          if (update_arg( (void *)&(args_info->filter_arg), 
               &(args_info->filter_orig), &(args_info->filter_given),
              &(local_args_info.filter_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "filter", 'F',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Filter output .  */
        
          if (update_multiple_arg_temp(&grep_list, 
              &(local_args_info.grep_given), optarg, 0, 0, ARG_STRING,
              "grep", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'E':	/* Environment variable.  */
        
          if (update_multiple_arg_temp(&env_list, 
              &(local_args_info.env_given), optarg, 0, 0, ARG_STRING,
              "env", 'E',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Number of concurrent connection threads.  */
        
        
          if (update_arg( (void *)&(args_info->concurrent_arg), 
               &(args_info->concurrent_orig), &(args_info->concurrent_given),
              &(local_args_info.concurrent_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "concurrent", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* Split logfile per host (needs --log-file).  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->log_split_given),
              &(local_args_info.log_split_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "log-split", 'S',
              additional_error))
            goto failure;
        
          break;
        case 'L':	/* Log to file instead of stdout.  */
        
        
          if (update_arg( (void *)&(args_info->log_file_arg), 
               &(args_info->log_file_orig), &(args_info->log_file_given),
              &(local_args_info.log_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "log-file", 'L',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "detailed-help") == 0) {
            cmdline_parser_print_detailed_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            cmdline_parser_print_full_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Print remote stdout.  */
          if (strcmp (long_options[option_index].name, "stdout") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->stdout_given),
                &(local_args_info.stdout_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "stdout", '-',
                additional_error))
              goto failure;
          
          }
          /* Print remote stderr.  */
          else if (strcmp (long_options[option_index].name, "stderr") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->stderr_given),
                &(local_args_info.stderr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "stderr", '-',
                additional_error))
              goto failure;
          
          }
          /* Path to plugins.  */
          else if (strcmp (long_options[option_index].name, "plugin-path") == 0)
          {
          
            if (update_multiple_arg_temp(&plugin_path_list, 
                &(local_args_info.plugin_path_given), optarg, 0, "/usr/local/share/distexec/plugins", ARG_STRING,
                "plugin-path", '-',
                additional_error))
              goto failure;
          
          }
          /* Date format.  */
          else if (strcmp (long_options[option_index].name, "log-format-date") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->log_format_date_arg), 
                 &(args_info->log_format_date_orig), &(args_info->log_format_date_given),
                &(local_args_info.log_format_date_given), optarg, 0, "%Y-%m-%d", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "log-format-date", '-',
                additional_error))
              goto failure;
          
          }
          /* Time format.  */
          else if (strcmp (long_options[option_index].name, "log-format-time") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->log_format_time_arg), 
                 &(args_info->log_format_time_orig), &(args_info->log_format_time_given),
                &(local_args_info.log_format_time_given), optarg, 0, "%H:%M:%S", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "log-format-time", '-',
                additional_error))
              goto failure;
          
          }
          /* Log format.  */
          else if (strcmp (long_options[option_index].name, "log-format") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->log_format_arg), 
                 &(args_info->log_format_orig), &(args_info->log_format_given),
                &(local_args_info.log_format_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "log-format", '-',
                additional_error))
              goto failure;
          
          }
          /* Enable debug messages.  */
          else if (strcmp (long_options[option_index].name, "debug") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->debug_flag), 0, &(args_info->debug_given),
                &(local_args_info.debug_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "debug", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->config_arg),
    &(args_info->config_orig), args_info->config_given,
    local_args_info.config_given, 0,
    ARG_STRING, config_list);
  multiple_default_value.default_string_arg = "/usr/local/share/distexec/plugins";
  update_multiple_arg((void *)&(args_info->plugin_path_arg),
    &(args_info->plugin_path_orig), args_info->plugin_path_given,
    local_args_info.plugin_path_given, &multiple_default_value,
    ARG_STRING, plugin_path_list);
  update_multiple_arg((void *)&(args_info->plugin_arg),
    &(args_info->plugin_orig), args_info->plugin_given,
    local_args_info.plugin_given, 0,
    ARG_STRING, plugin_list);
  update_multiple_arg((void *)&(args_info->grep_arg),
    &(args_info->grep_orig), args_info->grep_given,
    local_args_info.grep_given, 0,
    ARG_STRING, grep_list);
  update_multiple_arg((void *)&(args_info->env_arg),
    &(args_info->env_orig), args_info->env_given,
    local_args_info.env_given, 0,
    ARG_STRING, env_list);

  args_info->config_given += local_args_info.config_given;
  local_args_info.config_given = 0;
  args_info->plugin_path_given += local_args_info.plugin_path_given;
  local_args_info.plugin_path_given = 0;
  args_info->plugin_given += local_args_info.plugin_given;
  local_args_info.plugin_given = 0;
  args_info->grep_given += local_args_info.grep_given;
  local_args_info.grep_given = 0;
  args_info->env_given += local_args_info.env_given;
  local_args_info.env_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  free_list (config_list, 1 );
  free_list (plugin_path_list, 1 );
  free_list (plugin_list, 1 );
  free_list (grep_list, 1 );
  free_list (env_list, 1 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

#ifndef CONFIG_FILE_LINE_SIZE
#define CONFIG_FILE_LINE_SIZE 2048
#endif
#define ADDITIONAL_ERROR " in configuration file "

#define CONFIG_FILE_LINE_BUFFER_SIZE (CONFIG_FILE_LINE_SIZE+3)
/* 3 is for "--" and "=" */

static int
_cmdline_parser_configfile (const char *filename, int *my_argc)
{
  FILE* file;
  char my_argv[CONFIG_FILE_LINE_BUFFER_SIZE+1];
  char linebuf[CONFIG_FILE_LINE_SIZE];
  int line_num = 0;
  int result = 0, equal;
  char *fopt, *farg;
  char *str_index;
  size_t len, next_token;
  char delimiter;

  if ((file = fopen(filename, "r")) == 0)
    {
      fprintf (stderr, "%s: Error opening configuration file '%s'\n",
               CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  while ((fgets(linebuf, CONFIG_FILE_LINE_SIZE, file)) != 0)
    {
      ++line_num;
      my_argv[0] = '\0';
      len = strlen(linebuf);
      if (len > (CONFIG_FILE_LINE_BUFFER_SIZE-1))
        {
          fprintf (stderr, "%s:%s:%d: Line too long in configuration file\n",
                   CMDLINE_PARSER_PACKAGE, filename, line_num);
          result = EXIT_FAILURE;
          break;
        }

      /* find first non-whitespace character in the line */
      next_token = strspn (linebuf, " \t\r\n");
      str_index  = linebuf + next_token;

      if ( str_index[0] == '\0' || str_index[0] == '#')
        continue; /* empty line or comment line is skipped */

      fopt = str_index;

      /* truncate fopt at the end of the first non-valid character */
      next_token = strcspn (fopt, " \t\r\n=");

      if (fopt[next_token] == '\0') /* the line is over */
        {
          farg  = 0;
          equal = 0;
          goto noarg;
        }

      /* remember if equal sign is present */
      equal = (fopt[next_token] == '=');
      fopt[next_token++] = '\0';

      /* advance pointers to the next token after the end of fopt */
      next_token += strspn (fopt + next_token, " \t\r\n");

      /* check for the presence of equal sign, and if so, skip it */
      if ( !equal )
        if ((equal = (fopt[next_token] == '=')))
          {
            next_token++;
            next_token += strspn (fopt + next_token, " \t\r\n");
          }
      str_index  += next_token;

      /* find argument */
      farg = str_index;
      if ( farg[0] == '\"' || farg[0] == '\'' )
        { /* quoted argument */
          str_index = strchr (++farg, str_index[0] ); /* skip opening quote */
          if (! str_index)
            {
              fprintf
                (stderr,
                 "%s:%s:%d: unterminated string in configuration file\n",
                 CMDLINE_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }
      else
        { /* read up the remaining part up to a delimiter */
          next_token = strcspn (farg, " \t\r\n#\'\"");
          str_index += next_token;
        }

      /* truncate farg at the delimiter and store it for further check */
      delimiter = *str_index, *str_index++ = '\0';

      /* everything but comment is illegal at the end of line */
      if (delimiter != '\0' && delimiter != '#')
        {
          str_index += strspn(str_index, " \t\r\n");
          if (*str_index != '\0' && *str_index != '#')
            {
              fprintf
                (stderr,
                 "%s:%s:%d: malformed string in configuration file\n",
                 CMDLINE_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }

    noarg:
      if (!strcmp(fopt,"include")) {
        if (farg && *farg) {
          result = _cmdline_parser_configfile(farg, my_argc);
        } else {
          fprintf(stderr, "%s:%s:%d: include requires a filename argument.\n",
                  CMDLINE_PARSER_PACKAGE, filename, line_num);
        }
        continue;
      }
      len = strlen(fopt);
      strcat (my_argv, len > 1 ? "--" : "-");
      strcat (my_argv, fopt);
      if (len > 1 && ((farg && *farg) || equal))
        strcat (my_argv, "=");
      if (farg && *farg)
        strcat (my_argv, farg);
      ++(*my_argc);

      cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
      cmd_line_list_tmp->next = cmd_line_list;
      cmd_line_list = cmd_line_list_tmp;
      cmd_line_list->string_arg = gengetopt_strdup(my_argv);
    } /* while */

  if (file)
    fclose(file);
  return result;
}

int
cmdline_parser_configfile (
  const char *filename,
                           struct gengetopt_args_info *args_info,
                           int override, int initialize, int check_required)
{
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;
  
  return cmdline_parser_config_file (filename, args_info, &params);
}

int
cmdline_parser_config_file (const char *filename,
                           struct gengetopt_args_info *args_info,
                           struct cmdline_parser_params *params)
{
  int i, result;
  int my_argc = 1;
  char **my_argv_arg;
  char *additional_error;

  /* store the program name */
  cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
  cmd_line_list_tmp->next = cmd_line_list;
  cmd_line_list = cmd_line_list_tmp;
  cmd_line_list->string_arg = gengetopt_strdup (CMDLINE_PARSER_PACKAGE);

  result = _cmdline_parser_configfile(filename, &my_argc);

  if (result != EXIT_FAILURE) {
    my_argv_arg = (char **) malloc((my_argc+1) * sizeof(char *));
    cmd_line_list_tmp = cmd_line_list;

    for (i = my_argc - 1; i >= 0; --i) {
      my_argv_arg[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

    my_argv_arg[my_argc] = 0;

    additional_error = (char *)malloc(strlen(filename) + strlen(ADDITIONAL_ERROR) + 1);
    strcpy (additional_error, ADDITIONAL_ERROR);
    strcat (additional_error, filename);
    result =
      cmdline_parser_internal (my_argc, my_argv_arg, args_info,
                              params,
                              additional_error);

    free (additional_error);
    free (my_argv_arg);
  }

  free_cmd_list();
  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}
